# Generated by Django 4.1.4 on 2024-08-30 01:54

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Funding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base amount of money spent",
                        max_digits=19,
                    ),
                ),
                (
                    "purchased_via",
                    models.CharField(
                        choices=[
                            ("STRIPE", "Stripe"),
                            ("PAYPAL", "Paypal"),
                            ("MERCANTIL_PAGO_MOVIL", "Pago Movil - Mercantil"),
                        ],
                        default="STRIPE",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESSFUL", "Successful"), ("FAILED", "Failed")],
                        max_length=10,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="Reference string used to identify the transaction in other platforms",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The transaction's fee",
                        max_digits=19,
                    ),
                ),
                ("error", models.TextField(null=True)),
                (
                    "usd_exchange_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="USD exchange rate when the funding ocurred",
                        max_digits=19,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Movement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("GIFT_RECEIVED", "Gift received"),
                            ("GIFT_SENT", "Gift sent"),
                            ("GIFT_ACCEPTED", "Gift accepted"),
                            ("GIFT_REJECTED", "Gift rejected"),
                            ("GIFT_REFUNDED", "Gift refunded"),
                            ("GIFT_EXPIRED", "Gift expired"),
                            ("GIFT_CLAIMED", "Gift claimed"),
                            ("BAR_CLAIM_PAYMENT", "Payment to a bar due to gift claim"),
                            ("FUNDING", "Funding performed"),
                            ("ADMIN_FUNDING", "Funding performed by an admin"),
                            ("ADMIN_BAR_PAYMENT", "Payment to a bar by an admin"),
                            ("ADMIN_FUNDS_WITHDRAWAL", "Funds withdrawed by an admin"),
                            ("FUNDS_EXCHANGE_ORIGIN", "Currency exchange to "),
                            ("FUNDS_EXCHANGE_DESTINATION", "Currency exchange to "),
                        ],
                        max_length=26,
                    ),
                ),
                (
                    "grouping_id",
                    models.IntegerField(
                        help_text="Used to group two or more related movements together"
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RechargeFundsSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="IN_PROGRESS",
                        max_length=11,
                    ),
                ),
                (
                    "payment_platform",
                    models.CharField(
                        choices=[
                            ("STRIPE", "Stripe"),
                            ("PAYPAL", "Paypal"),
                            ("MERCANTIL_PAGO_MOVIL", "Pago Movil - Mercantil"),
                        ],
                        default="STRIPE",
                        max_length=20,
                    ),
                ),
                (
                    "order",
                    models.CharField(
                        help_text="String used to identify the transaction in other platforms, the naming changes accordingly, for example these are called PaymentIntents in Stripe",
                        max_length=255,
                    ),
                ),
                ("request_idempotency_key", models.UUIDField()),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StoreFundAccount",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("VES", "local_currency"),
                            ("USD", "Dollars"),
                            ("MOBILE_PAY", "Mobile payments (Pago Móvil)"),
                            ("PAYPAL", "Paypal"),
                        ],
                        default="USD",
                        max_length=10,
                    ),
                ),
                ("number", models.TextField(null=True)),
                ("holder_name", models.TextField(null=True)),
                ("bank_name", models.TextField(null=True)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[("RIF", "Rif"), ("CI", "Cedula")],
                        max_length=14,
                        null=True,
                    ),
                ),
                ("doc_number", models.TextField(null=True)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, null=True, region=None
                    ),
                ),
                ("is_preferential", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StorePayment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount paid to the Store",
                        max_digits=19,
                    ),
                ),
                (
                    "reference",
                    models.IntegerField(
                        help_text="Payment reference to be displayed to end users",
                        null=True,
                        unique=True,
                    ),
                ),
                ("receipt", models.FileField(upload_to="stores")),
                (
                    "usd_exchange_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="USD exchange rate when the payment ocurred",
                        max_digits=19,
                    ),
                ),
                (
                    "funds_account_origin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administration.fundaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
    ]
