# Generated by Django 4.1.4 on 2024-08-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "read",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the User has read or not the notification",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("FOLLOWED", "Followed"),
                            ("GIFT_ACCEPTED", "Regalo aceptado"),
                            ("GIFT_RECEIVED", "🍺 Te han enviado un regalo!"),
                            ("GIFT_REJECTED", "Regalo rechazado"),
                        ],
                        default="GIFT_RECEIVED",
                        max_length=23,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
    ]
